CREATE TABLE USERS
(    
    ID INT not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),   
    USERNAME VARCHAR(20) NOT NULL,     
    PASSWORD VARCHAR(20) NOT NULL,
    USERTYPE VARCHAR(20) NOT NULL
);

CREATE TABLE CUSTOMER
(    
    ID INT not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),   
    ADDRESS VARCHAR(60) NOT NULL,
    USERID INT,
    CONSTRAINT FK_USER_ID_CUSTOMER FOREIGN KEY (USERID) REFERENCES USERS(ID)
);

CREATE TABLE DRIVER
(    
    ID INT not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),   
    REGISTRATION VARCHAR(10) NOT NULL,
    USERID INT,
    CONSTRAINT FK_USER_ID_DRIVER FOREIGN KEY (USERID) REFERENCES USERS(ID)
);

CREATE TABLE JOURNEY
(
    ID INT not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    ORIGIN VARCHAR(60) NOT NULL,
    DESTINATION VARCHAR(60) NOT NULL,
    PRICE DOUBLE,
    DISTANCE DOUBLE,
    DEPARTURETIME TIME NOT NULL,
    DEPARTUREDATE DATE NOT NULL,
    CUSTOMERID INT NOT NULL,
    DRIVERID INT,
    COMPLETED INT DEFAULT 0,
    PAID INT DEFAULT 0,
    CONSTRAINT FK_CUSTOMER_ID_JOURNEY FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(ID),
    CONSTRAINT FK_DRIVER_ID_JOURNEY FOREIGN KEY (DRIVERID) REFERENCES DRIVER(ID)
);

CREATE TABLE AVAILABILITY
(
    ID INT not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    STARTDATE DATE NOT NULL,
    ENDDATE DATE NOT NULL,
    DRIVERID INT,
    CONSTRAINT FK_DRIVER_ID_AVAILABILITY FOREIGN KEY (DRIVERID) REFERENCES DRIVER(ID)

);

INSERT INTO USERS(USERNAME, PASSWORD, USERTYPE)
VALUES('administrator', 'password', 'admin');
